Chain Agnostic Standards Alliance Readme :)
ChainAgnostic/CASA pull request #2
Opened 2020-12-04 15:14 UTC by antoineherzog

2020-12-04 15:15 UTC, antoineherzog commented
Here we go! @ligi @pedrouid

2020-12-05 08:36 UTC, ligi requested changes

2020-12-05 08:36 UTC, ligi commented on README.md
> +The CASA is a autonomous alliance dedicated to write standard for blockchain protocol that are not specific to a single chain. It aims to have collaborators from all the crypto-space. The initiative
```suggestion
The CASA is a autonomous alliance dedicated to write standards for blockchain protocols that are not specific to a single chain. It aims to have collaborators from all the crypto-space. The initiative emerged from a few crypto community members that self-organize with the objective of having unified and efficient process that include the whole ecosystem. It aims to make the crypto more seamless and more interoperable between protocols, software and companies.
```

2020-12-05 08:36 UTC, ligi commented on README.md
> +The CASA have the only goal to organize working group, be a place where all proposals are gathered and to publish final CAIPs and implementation proposals that could be adopted by the community.
```suggestion
The CASA has the only goal to organize working groups, be a place where all proposals are gathered and to publish final CAIPs and implementation proposals that could be adopted by the community. 
```

2020-12-05 08:36 UTC, ligi commented on README.md
> +| Working Groups            | Collections of members tackling specific areas of interest, such as Ceramic governance or identity. |
can you elaborate on "Ceramic"? I am missing context here

2020-12-06 11:09 UTC, antoineherzog commented
I fixed all the sentences and removed the sentence about ceramic (it was a remaining copy paste from the template). Please re-check

2020-12-07 12:32 UTC, ligi approved these changes

2020-12-07 12:32 UTC, ligi commented
Thanks for the changes - LGTM now - but would love some more eyeballs on it - hope @pedrouid has a chance to review it

2020-12-09 02:53 UTC, ligi commented
I will merge end of the week if we get no veto. Last time to chime in @pedrouid @webmaster128 @rekmarks  et all.

2020-12-09 16:10 UTC, pedrouid approved these changes
👍

2020-12-09 16:10 UTC, pedrouid commented
LGTM 👍

2020-12-11 09:56 UTC, antoineherzog commented
@ligi Can you merge today? I am going to talk about CASA on my speech sunday night at Cosmos Conversation Event :)

2020-12-11 10:14 UTC, merged