reorg readme, add board membership section
ChainAgnostic/CASA pull request #62
Opened 2022-12-22 17:27 UTC by bumblefudge

addressing user input received over email

2022-12-22 17:32 UTC, ligi requested changes

2022-12-22 17:32 UTC, ligi commented on README.md
> +Note that we tried (but failed) to find more info from the CASA website on the above.
?

2022-12-22 17:46 UTC, bumblefudge commented on README.md
> +Note that we tried (but failed) to find more info from the CASA website on the above.
extreme cringe 🤦‍♀️

2022-12-26 16:20 UTC, ligi approved these changes
:+1:

2022-12-26 16:20 UTC, merged