add eth addresses to board section
ChainAgnostic/CASA pull request #77
Opened 2023-03-09 21:19 UTC by bumblefudge

as per today's treasury meeting

2023-03-13 11:44 UTC, oed commented on README.md
> +- eip155:1:0x5c44E8982fa3C3239C6E3C5be2cc6663c7C9387E
This is not me. I don't own this ENS name!
Please use this instead:
```
0x9fA6c303300ed23CeFB0b1106aE898810DC01cC3
```

2023-03-14 17:02 UTC, ritave requested changes

2023-03-14 17:02 UTC, ritave commented on README.md
> +- eip155:1:0xcBec15583A21C3ddAD5fab658be5b4FE85Df730b
The addresses should be near the names of the board members, not in a separate paragraph

2023-03-15 22:25 UTC, obstropolos approved these changes

2023-03-16 09:17 UTC, oed approved these changes

2023-03-23 18:52 UTC, merged